config/routes.rb
Rails.application.routes.draw do
  match ':trap_uri(.:format)', to: 'requests#create', via: [:post, :put, :get, :delete, :patch]
  scope ':trap_uri' do
    resources :requests, only: [:index, :show] do
      get :stream, on: :member
    end
  end
end

app/models/trap.rb
class Trap < ActiveRecord::Base
  validates :uri, presence: true, uniqueness: true, length: { maximum: 255 }

  has_many :requests, class_name: 'Trap::Request'
end

app/models/trap/request.rb
class Trap::Request < ActiveRecord::Base
  belongs_to :trap

  serialize :query_params,  JSON
  serialize :cookies,       JSON
  serialize :headers,       JSON
  serialize :response,      JSON

  scope :desc_by_created, -> { order(created_at: :desc) }
  scope :last_created,    -> { desc_by_created.limit(1) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  rescue_from ActiveRecord::RecordNotFound, with: :render_404

  [403, 404, 500].each do |num|
    define_method :"show_#{num}" do
      render file: "#{Rails.root}/public/#{num}.html", layout: false, status: num
    end
  end

  protected

  def render_error(message, code = 500)
    respond_to do |format|
      format.html { send("show_#{code}") }
      format.json { render json: { error: message }, status: code }
    end
    false
  end

  def render_404
    render_error('404 page not found', 404)
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :find_a_trap
  after_action :update_response, only: [:index]
  skip_before_action :verify_authenticity_token, only: [:create]

  # [*] /:trap_id
  def create
    @req = TrapRequestCreate.new(request, @trap).create!
    respond_to do |format|
      format.html { render text: "request logged, id: #{@req.id}" }
      format.json { render json: { id: @req.id }, status: 500 }
    end
  rescue => e
    render_error(e.message)
  end

  # GET /:trap_uri/requests
  def index; end

  # GET /:trap_uri/requests/:id
  def show
    @request = @trap.requests.find(params[:id])
  end

  # GET /:trap_uri/requests/:id/stream
  def stream
    response.headers['Content-Type'] = 'text/event-stream'

    last_request = @trap.requests.last_created.first
    io_write(last_request) if recently_changed? last_request
  ensure
    response.stream.close
  end

  private

  def io_write(last_request)
    response.stream.write("event: results\n")
    tpl = render_to_string(partial: '/trap/requests/request.html.erb', locals: { request: last_request }).delete("\n")
    response.stream.write("data: #{tpl}\n\n")
  end

  def update_response
    @req.update!(response: response.body) if @req
  end

  def find_a_trap
    @trap = Trap.find_by_uri(params[:trap_uri])
    fail ActiveRecord::RecordNotFound if @trap.nil?
  end

  def recently_changed?(request)
    request.created_at > 2.seconds.ago
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_json(obj)
    %(<pre>#{JSON.pretty_generate(obj)}</pre></code>).html_safe unless obj.blank?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RequestsTrap</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
  <%= yield :javascript %>
  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/requests/index.html.erb
<h1>Requests</h1>

<table class="table table-striped table-hover table-bordered">
  <thead>
  <tr>
    <th>ID</th>
    <th>Date & Time</th>
    <th>URI</th>
  </tr>
  </thead>

  <tbody id="requests">
    <%= render @trap.requests.desc_by_created %>
  </tbody>
</table>

<% content_for :javascript do %>
  <script type="text/javascript">
    window.stream_path = '<%= stream_request_path(trap_uri: @trap.uri, id: @trap.id) %>';
  </script>
<% end %>

app/views/requests/show.html.erb
<h1>Request</h1>

<table class="table table-striped table-hover table-bordered">
  <tr>
    <td>ID</td>
    <td><%= @request.id %></td>
  </tr>
  <tr>
    <td>Date & Time</td>
    <td><%= l @request.created_at %></td>
  </tr>
  <tr>
    <td>Remote IP</td>
    <td><%= @request.remote_ip %></td>
  </tr>
  <tr>
    <td>Request method</td>
    <td><%= @request.request_method %></td>
  </tr>
  <tr>
    <td>Scheme</td>
    <td><%= @request.scheme %></td>
  </tr>
  <tr>
    <td>Query string</td>
    <td><%= @request.query_string %></td>
  </tr>
  <tr>
    <td>Query params</td>
    <td><%= show_json @request.query_params %></td>
  </tr>
  <tr>
    <td>Cookies</td>
    <td><%= show_json @request.cookies %></td>
  </tr>
  <tr>
    <td>Headers</td>
    <td><%= show_json @request.headers %></td>
  </tr>
  <tr>
    <td colspan="2">
      <h3>Response</h3>
      <pre><%= @request.response %></pre>
    </td>
  </tr>
</table>

app/views/trap/requests/_request.html.erb
<tr>
  <td><%= request.id %></td>
  <td><%= l request.created_at %></td>
  <td><%= link_to request.query_string, request_path(trap_uri: request.trap.uri, id: request.id) %></td>
</tr>